### ISSUE TITLE
something error

### ISSUE THREAD

**Issue by pengxinzhe** [nthjelme/nodejs-domino#3]
```
D:\Lotus\nodejs>node -v
v5.1.0

D:\Lotus\nodejs>node index.js
module.js:450
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\D:\Lotus\nodejs\node_modules\domino-nsf\lib\Release\addon.node
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Lotus\nodejs\node_modules\domino-nsf\index.js:1:80)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)`
```

**Comment by edm00se** [comment]
Are you using node 32-bit or 64-bit?

If you're uncertain, try pasting back the output of:
`node -e 'console.log(process);'`

Specifically the `arch` property is relevant.

**Comment by pengxinzhe** [comment]
node 32-bit

```
  versions:
   { http_parser: '2.6.0',
     node: '5.1.0',
     v8: '4.6.85.31',
     uv: '1.7.5',
     zlib: '1.2.8',
     ares: '1.10.1-DEV',
     icu: '56.1',
     modules: '47',
     openssl: '1.0.2d' },
  arch: 'ia32',
  platform: 'win32',
```

**Comment by edm00se** [comment]
Curious, my environment which I can confirm as working is negligibly different, my output reads:

``` js
...
versions:
   { http_parser: '2.6.2',
     node: '5.10.1',
     v8: '4.6.85.31',
     uv: '1.8.0',
     zlib: '1.2.8',
     ares: '1.10.1-DEV',
     icu: '56.1',
     modules: '47',
     openssl: '1.0.2g' },
  arch: 'ia32',
  platform: 'win32',
...
```

Are you certain you have Notes client (32-bit) installed and set up correctly?
